# Generated by Django 5.2.6 on 2025-11-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique identifier (e.g., 'Ultimaker #1', 'Ultimaker #2')", max_length=100)),
                ('machine_name', models.CharField(help_text="Model/Type (e.g., 'Ultimaker S5')", max_length=200)),
                ('category', models.CharField(choices=[('Laser', 'Laser'), ('Vinyl', 'Vinyl'), ('Woodworking', 'Woodworking'), ('Textile', 'Textile'), ('Metalworking', 'Metalworking'), ('3D Printing', '3D Printing'), ('Electronics', 'Electronics')], max_length=50)),
                ('location', models.CharField(choices=[('Hatch Front (2nd Floor)', 'Hatch Front (2nd Floor)'), ('Hatch Back (2nd Floor)', 'Hatch Back (2nd Floor)'), ('Prototyping Studio (3rd Floor)', 'Prototyping Studio (3rd Floor)'), ('Prototyping Shop (3rd Floor)', 'Prototyping Shop (3rd Floor)')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('requires_level_1', models.BooleanField(default=False)),
                ('requires_level_2', models.BooleanField(default=False)),
                ('requires_level_3', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
