# Generated by Django 5.2.6 on 2025-11-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='machines/images/'),
        ),
        migrations.AddField(
            model_name='machine',
            name='mac_address',
            field=models.CharField(blank=True, help_text='MAC address (e.g., 00:1B:44:11:3A:B7)', max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='year_bought',
            field=models.IntegerField(blank=True, help_text='Year the machine was purchased', null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
