# Generated by Django 5.2.6 on 2025-11-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_machine_image_machine_mac_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='map_position_x',
            field=models.FloatField(blank=True, help_text='X position on floorplan (0-100%)', null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='map_position_y',
            field=models.FloatField(blank=True, help_text='Y position on floorplan (0-100%)', null=True),
        ),
    ]
