# Generated by Django 5.2.8 on 2025-11-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_machine_image_machine_mac_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo of the machine.', null=True, upload_to='machines/images/'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mac_address',
            field=models.CharField(blank=True, help_text='MAC address, for example 00:1B:44:11:3A:B7.', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_name',
            field=models.CharField(help_text="Model or type, for example 'Ultimaker S5', 'Epilog Fusion Pro'.", max_length=200),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(help_text="Unique identifier, for example 'Ultimaker #1', 'Epilog Laser #2'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='machine',
            name='year_bought',
            field=models.IntegerField(blank=True, help_text='Year this machine was purchased.', null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='required_trainings',
            field=models.ManyToManyField(blank=True, help_text='Specific training(s) a student must complete to use this machine.', related_name='machines', to='machines.trainingtype'),
        ),
    ]
