# Generated by Django 5.2.8 on 2025-11-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_machine_map_position_x_machine_map_position_y'),
        ('machines', '0003_trainingtype_alter_machine_image_and_more'),
    ]

    operations = [
    ]
