
# Generated by Django 5.2.8 on 2025-11-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_merge_20251120_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='map_position_x',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='map_position_y',
        ),
    ]
