# Generated by Django 5.2.6 on 2025-11-20 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('machines', '0005_remove_machine_map_position_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='map_position_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='map_position_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='locations.location'),
        ),
    ]
