# Generated by Django 5.2.6 on 2025-11-20 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('machines', '0006_machine_map_position_x_machine_map_position_y_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['category', 'machine_name', 'name']},
        ),
        migrations.AlterField(
            model_name='machine',
            name='location',
            field=models.ForeignKey(help_text='Physical location of this machine', on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='map_position_x',
            field=models.FloatField(blank=True, help_text='X position on floorplan (0-100%)', null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='map_position_y',
            field=models.FloatField(blank=True, help_text='Y position on floorplan (0-100%)', null=True),
        ),
    ]
