# Generated by Django 5.2.8 on 2025-11-25 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_merge_20251120_1522'),
        ('machines', '0007_alter_machine_options_alter_machine_location_and_more'),
    ]

    operations = [
    ]
