# Generated by Django 5.2.6 on 2025-11-29 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_merge_20251124_2256'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Machine type name (e.g., 'Prusa MK3S+')", max_length=100)),
                ('category', models.CharField(choices=[('Laser', 'Laser'), ('Vinyl', 'Vinyl'), ('Woodworking', 'Woodworking'), ('Textile', 'Textile'), ('Metalworking', 'Metalworking'), ('3D Printing', '3D Printing'), ('Electronics', 'Electronics')], help_text="Category (e.g., '3D Printing', 'Laser')", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of this machine type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='machine_types/')),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('documentation_url', models.URLField(blank=True, help_text='Link to documentation/manual')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Machine Type',
                'verbose_name_plural': 'Machine Types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_type',
            field=models.ForeignKey(blank=True, help_text='Link to machine type for training requirements', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_instances', to='machines.machinetype'),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Training name (e.g., 'Intro to 3D Printing')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this training covers')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1 - Introduction'), (2, 'Level 2 - Intermediate'), (3, 'Level 3 - Advanced')], default=1)),
                ('category', models.CharField(help_text="Category (e.g., '3D Printing', 'Laser')", max_length=50)),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Expected duration in minutes')),
                ('max_participants', models.PositiveIntegerField(default=4, help_text='Maximum participants per session')),
                ('materials_url', models.URLField(blank=True, help_text='Link to training materials')),
                ('video_url', models.URLField(blank=True, help_text='Link to training video')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('draft', 'Draft')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trainings', to=settings.AUTH_USER_MODEL)),
                ('machine_types', models.ManyToManyField(blank=True, help_text='Machine types this training qualifies users for', related_name='trainings', to='machines.machinetype')),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='Trainings required before taking this one', related_name='unlocks', to='machines.training')),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
                'ordering': ['category', 'level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserTrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='completed', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_trainings', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_records', to='machines.training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Training Record',
                'verbose_name_plural': 'User Training Records',
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'training')},
            },
        ),
    ]
