# Generated by Django 5.2.6 on 2025-11-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_machinetype_machine_machine_type_training_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='machine_types',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='machine_type',
        ),
        migrations.AddField(
            model_name='training',
            name='machine_type_names',
            field=models.JSONField(blank=True, default=list, help_text='List of machine_name values this training qualifies users for'),
        ),
        migrations.DeleteModel(
            name='MachineType',
        ),
    ]
