# Generated by Django 5.2.6 on 2025-11-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0010_remove_training_machine_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='documentation_url',
            field=models.URLField(blank=True, help_text='Link to user manual or documentation'),
        ),
        migrations.AddField(
            model_name='machine',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Manufacturer name (e.g., Ultimaker, Prusa Research)', max_length=100),
        ),
        migrations.AddField(
            model_name='machine',
            name='model_number',
            field=models.CharField(blank=True, help_text='Model number (e.g., S5, MK3S+)', max_length=100),
        ),
    ]
