# Generated by Django 5.2.6 on 2025-11-29 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0011_machine_documentation_url_machine_manufacturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'Laser', '3D Printing')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this category')),
                ('icon', models.CharField(blank=True, help_text='Emoji icon for the category', max_length=10)),
                ('color', models.CharField(blank=True, default='#293242', help_text='Color code for UI display', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display categories')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Machine Category',
                'verbose_name_plural': 'Machine Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='category_fk',
            field=models.ForeignKey(blank=True, help_text='Machine category (new)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='machines.machinecategory'),
        ),
    ]
