# Generated by Django 5.2.6 on 2025-11-30 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0012_machinecategory_machine_category_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='is_reservable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='required_training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.training'),
        ),
    ]
