# Generated by Django 5.2.6 on 2025-11-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0013_machine_is_reservable_machine_required_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='documentation_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
