# Generated by Django 5.2.8 on 2025-12-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0014_alter_machine_documentation_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Manufacturer name (e.g., Ultimaker, Prusa Research)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='model_number',
            field=models.CharField(blank=True, help_text='Model number (e.g., S5, MK3S+)', max_length=100, null=True),
        ),
    ]
