# Generated by Django 5.2.6 on 2025-12-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0015_alter_machine_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('broken', 'Broken'), ('maintenance', 'Maintenance')], default='active', help_text='Whether the machine is working, broken, or under maintenance.', max_length=20),
        ),
    ]
