# Generated by Django 5.2.6 on 2025-11-29 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Fall 2025'", max_length=100)),
                ('semester_type', models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], max_length=10)),
                ('year', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('holidays', models.JSONField(blank=True, default=list, help_text="List of holiday dates in ISO format ['2025-11-28', '2025-12-25']")),
                ('is_active', models.BooleanField(default=False, help_text='Only one semester can be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('semester_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='SchedulePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('week_start_date', models.DateField(help_text='Week being published')),
                ('calendar_invites_sent', models.BooleanField(default=False)),
                ('calendar_invites_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='scheduling.semester')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Woodshop Combined'", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locations', models.ManyToManyField(related_name='groups', to='locations.location')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_groups', to='scheduling.semester')),
            ],
            options={
                'ordering': ['semester', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('shift_type', models.CharField(choices=[('open_hours', 'Open Hours Hosting'), ('training', 'Training Available'), ('floater', 'Floater')], max_length=20)),
                ('team_category', models.CharField(blank=True, help_text='Machine category for training availability', max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('swap_requested', 'Swap Requested'), ('swap_approved', 'Swap Approved'), ('amendment_requested', 'Amendment Requested'), ('amendment_approved', 'Amendment Approved')], default='scheduled', max_length=30)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shifts', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='locations.location')),
                ('location_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='scheduling.locationgroup')),
                ('original_user', models.ForeignKey(blank=True, help_text='Original user before swap', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swapped_shifts', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='scheduling.semester')),
                ('swap_requested_with', models.ForeignKey(blank=True, help_text='User requested to swap with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_requests_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('swap', 'Shift Swap'), ('amendment', 'Amendment'), ('cancellation', 'Cancellation')], max_length=20)),
                ('swap_accepted_by_other_user', models.BooleanField(default=False)),
                ('proposed_date', models.DateField(blank=True, null=True)),
                ('proposed_start_time', models.TimeField(blank=True, null=True)),
                ('proposed_end_time', models.TimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_approved', 'Auto-Approved')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='scheduling.shift')),
                ('swap_with_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_targets', to='scheduling.shift')),
                ('swap_with_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_offers_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('hosts_required', models.IntegerField(default=1, help_text='Number of hosts needed for this location/group')),
                ('floaters_required', models.IntegerField(default=0, help_text='Number of floaters needed (not location-specific)')),
                ('is_peak_hours', models.BooleanField(default=False)),
                ('location', models.ForeignKey(blank=True, help_text='Individual location needing hosts', null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
                ('location_group', models.ForeignKey(blank=True, help_text='Or a group of locations needing hosts', null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.locationgroup')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requirements', to='scheduling.semester')),
            ],
            options={
                'ordering': ['semester', 'day_of_week', 'time_start'],
            },
        ),
        migrations.CreateModel(
            name='TeamMemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, help_text='Machine category: Laser, 3D Printing, Woodworking, etc.', max_length=50)),
                ('role', models.CharField(choices=[('team_member', 'Team Member'), ('team_lead', 'Team Lead'), ('floater', 'Floater'), ('staff', 'Staff')], default='team_member', max_length=20)),
                ('expected_weekly_hours', models.IntegerField(default=10, help_text='Expected hours per week to work')),
                ('shift_preference', models.CharField(choices=[('few_long', 'Few Long Shifts'), ('many_short', 'Many Short Shifts'), ('no_preference', 'No Preference')], default='no_preference', max_length=20)),
                ('semester_overrides', models.JSONField(blank=True, default=dict, help_text="Semester-specific hours: {'fall2025': 15, 'spring2026': 8}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Unavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.CharField(blank=True, help_text='Optional reason', max_length=200)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='scheduling.semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Unavailabilities',
                'ordering': ['semester', 'user', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DailyOperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('space_open_time', models.TimeField(help_text='When the physical space opens')),
                ('space_close_time', models.TimeField(help_text='When the physical space closes')),
                ('open_hours_start', models.TimeField(help_text='When open hours hosting begins')),
                ('open_hours_end', models.TimeField(help_text='When open hours hosting ends')),
                ('training_start', models.TimeField(help_text='When training sessions can be scheduled')),
                ('training_end', models.TimeField(help_text='When training sessions end')),
                ('is_closed', models.BooleanField(default=False, help_text='Is the space closed this day?')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='scheduling.semester')),
            ],
            options={
                'verbose_name_plural': 'Daily Operating Hours',
                'ordering': ['semester', 'day_of_week'],
                'unique_together': {('semester', 'day_of_week')},
            },
        ),
    ]
