# Generated by Django 5.2.6 on 2025-11-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='team_category',
            field=models.CharField(blank=True, help_text='Machine category for training availability', max_length=50, null=True),
        ),
    ]
