# Generated by Django 5.2.6 on 2025-11-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('scheduling', '0002_alter_shift_team_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationgroup',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='dailyoperatinghours',
            name='space_close_time',
        ),
        migrations.RemoveField(
            model_name='dailyoperatinghours',
            name='space_open_time',
        ),
        migrations.RemoveField(
            model_name='locationgroup',
            name='semester',
        ),
        migrations.AlterField(
            model_name='dailyoperatinghours',
            name='open_hours_end',
            field=models.TimeField(blank=True, help_text='When open hours hosting ends', null=True),
        ),
        migrations.AlterField(
            model_name='dailyoperatinghours',
            name='open_hours_start',
            field=models.TimeField(blank=True, help_text='When open hours hosting begins', null=True),
        ),
        migrations.AlterField(
            model_name='dailyoperatinghours',
            name='training_end',
            field=models.TimeField(blank=True, help_text='When training sessions end', null=True),
        ),
        migrations.AlterField(
            model_name='dailyoperatinghours',
            name='training_start',
            field=models.TimeField(blank=True, help_text='When training sessions can be scheduled', null=True),
        ),
        migrations.AlterField(
            model_name='shiftrequirement',
            name='floaters_required',
            field=models.PositiveIntegerField(default=0, help_text='Number of floaters needed (not location-specific)'),
        ),
        migrations.AlterField(
            model_name='shiftrequirement',
            name='hosts_required',
            field=models.PositiveIntegerField(default=0, help_text='Number of hosts needed for this location/group'),
        ),
        migrations.AlterUniqueTogether(
            name='shiftrequirement',
            unique_together={('semester', 'day_of_week', 'time_start', 'time_end', 'location', 'location_group')},
        ),
    ]
