# Generated by Django 5.2.6 on 2025-11-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_locationgroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyoperatinghours',
            name='training_disabled',
            field=models.BooleanField(default=False, help_text='Disable training on this day (even if closed)'),
        ),
    ]
