# Generated by Django 5.2.6 on 2025-11-29 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_dailyoperatinghours_training_disabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unavailability',
            options={'ordering': ['user', 'day_of_week', 'start_time'], 'verbose_name_plural': 'Unavailabilities'},
        ),
        migrations.AddField(
            model_name='teammemberprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Inactive members won't be scheduled"),
        ),
        migrations.AddField(
            model_name='teammemberprofile',
            name='is_trainer',
            field=models.BooleanField(default=False, help_text='Can this member conduct training sessions?'),
        ),
        migrations.AddField(
            model_name='teammemberprofile',
            name='max_weekly_hours',
            field=models.IntegerField(default=15, help_text='Maximum hours per week'),
        ),
        migrations.AddField(
            model_name='teammemberprofile',
            name='min_weekly_hours',
            field=models.IntegerField(default=0, help_text='Minimum hours per week'),
        ),
        migrations.AddField(
            model_name='teammemberprofile',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='scheduling.semester'),
        ),
        migrations.AddField(
            model_name='unavailability',
            name='is_unavailable',
            field=models.BooleanField(default=False, help_text='If true, user is unavailable. If false, times indicate availability.'),
        ),
        migrations.AlterField(
            model_name='teammemberprofile',
            name='expected_weekly_hours',
            field=models.IntegerField(default=10, help_text='Expected hours per week to work (deprecated, use max)'),
        ),
        migrations.AlterField(
            model_name='unavailability',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unavailability',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='scheduling.semester'),
        ),
        migrations.AlterField(
            model_name='unavailability',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='unavailability',
            unique_together={('user', 'semester', 'day_of_week')},
        ),
    ]
