# Generated by Django 5.2.6 on 2025-11-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_alter_unavailability_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived semesters are hidden from normal view'),
        ),
    ]
