# Generated by Django 5.2.6 on 2025-11-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_semester_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulepublication',
            name='calendar_invites_sent_at',
        ),
        migrations.RemoveField(
            model_name='schedulepublication',
            name='week_start_date',
        ),
        migrations.AddField(
            model_name='schedulepublication',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedulepublication',
            name='recipients_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedulepublication',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('partial', 'Partial'), ('failed', 'Failed')], default='sent', max_length=20),
        ),
        migrations.AddField(
            model_name='schedulepublication',
            name='weeks_count',
            field=models.IntegerField(default=0),
        ),
    ]
