# Generated by Django 5.2.9 on 2025-12-03 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_teammemberprofile_birthday_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unavailability',
            unique_together=set(),
        ),
    ]
