# Generated by Django 5.2.6 on 2025-12-04 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('scheduling', '0009_alter_unavailability_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWeekShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('shift_type', models.CharField(choices=[('open_hours', 'Open Hours Hosting'), ('training', 'Training Available'), ('floater', 'Floater')], max_length=20)),
                ('team_category', models.CharField(blank=True, help_text='Machine category for training availability', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_week_shifts', to='locations.location')),
                ('location_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_week_shifts', to='scheduling.locationgroup')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_week_shifts', to='scheduling.semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_week_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model Week Shift',
                'verbose_name_plural': 'Model Week Shifts',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
