# Generated by Django 5.2.6 on 2025-12-04 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_modelweekshift'),
        ('scheduling', '0010_unavailability_admin_notes_and_more'),
    ]

    operations = [
    ]
