# Generated by Django 5.2.7 on 2025-11-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='Department', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='is_team_lead',
            field=models.BooleanField(default=False, help_text='Designated to lead other team members (for Team Member role)'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='users/profile_pictures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, choices=[('', 'Select School'), ('MCAS', 'MCAS - Morrissey College of Arts and Sciences'), ('CSOM', 'CSOM - Carroll School of Management'), ('CSON', 'CSON - Connell School of Nursing'), ('LSEHD', 'LSEHD - Lynch School of Education and Human Development')], help_text='School', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Collaborator', 'Collaborator'), ('Team Member', 'Team Member'), ('Team Lead', 'Team Lead'), ('Staff', 'Staff'), ('Admin', 'Admin')], default='User', max_length=20),
        ),
    ]
