# Generated by Django 5.2.7 on 2025-11-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_department_user_is_team_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_team_lead',
            field=models.BooleanField(default=False, help_text='Designated to lead other team members (only applies to Team Member role)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Collaborator', 'Collaborator'), ('Team Member', 'Team Member'), ('Staff', 'Staff')], default='User', max_length=20),
        ),
    ]
