# Generated by Django 5.2.8 on 2025-11-07 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role_alter_studentprofile_user_trainerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('required_training_level', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MachineInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='available', max_length=30)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='accounts.machine')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELED', 'Canceled')], default='CONFIRMED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_reservations', to='accounts.machineinstance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_reservations', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['trainer', 'start_time'], name='accounts_tr_trainer_f27006_idx'), models.Index(fields=['trainer', 'end_time'], name='accounts_tr_trainer_068f3b_idx')],
            },
        ),
    ]
