# Generated by Django 5.2.6 on 2025-11-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_traineravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trainer',
            field=models.BooleanField(default=False, help_text='Can this team member conduct training sessions?'),
        ),
        migrations.AddField(
            model_name='user',
            name='team_assignment',
            field=models.CharField(blank=True, help_text='Machine category/team this member belongs to (e.g., Laser Cutting, 3D Printing)', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_team_lead',
            field=models.BooleanField(default=False, help_text='Is this team member a team lead?'),
        ),
    ]
