# Generated by Django 5.2.7 on 2025-11-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_machine_machineinstance_trainingreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Collaborator', 'Collaborator'), ('Team Member', 'Team Member'), ('Staff', 'Staff')], default='User', max_length=20),
        ),
    ]
