# Generated by Django 5.2.7 on 2025-11-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_machine_machineinstance_trainingreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='birthday',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_year',
            field=models.IntegerField(blank=True, help_text='Expected graduation year (e.g., 2025)', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='role_specification',
            field=models.CharField(blank=True, help_text="Additional role details (e.g., 'Undergraduate', 'Graduate Student')", max_length=100),
        ),
    ]
