# Generated by Django 5.2.6 on 2025-11-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_trainer_user_team_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_team_lead',
            field=models.BooleanField(default=False, help_text='Is this team member a team lead? (Team leads are automatically trainers)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team_assignment',
            field=models.CharField(blank=True, help_text='Machine category/team this member belongs to (required for team leads)', max_length=100),
        ),
    ]
