# Generated by Django 5.2.6 on 2025-11-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Hatch Front, Prototyping Studio', max_length=100)),
                ('building', models.CharField(help_text='e.g., 245 Beacon St', max_length=200)),
                ('floor', models.CharField(help_text='e.g., 3rd Floor', max_length=50)),
                ('num_stations', models.IntegerField(help_text='Number of tables/workstations')),
                ('capacity', models.IntegerField(help_text='Maximum number of people')),
                ('machine_types', models.TextField(help_text='Comma-separated list (e.g., Woodworking, Metalworking, 3D Printing)')),
                ('floorplan_image', models.ImageField(blank=True, help_text='Upload a floorplan image for this location', null=True, upload_to='floorplans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['building', 'floor', 'name'],
            },
        ),
    ]
